### ISSUE TITLE
Remove PE_MEMBER logic that is no longer relevant

### ISSUE THREAD

**Issue by rsdunlapiv** [NOAA-EMC/NEMS#103]
The PE_MEMBER logic in NEMS and the model_configure is no longer relevant and should be removed.  This remains historically from a prior version of NEMS that supported ensembles in the same MPI world.

See here:
https://github.com/NOAA-EMC/NEMS/blob/b593c6c56d6bc3644af69370127f9e99d22b4a1d/src/module_NEMS_GRID_COMP.F90#L279

and here:
https://github.com/NOAA-EMC/NEMS/blob/b593c6c56d6bc3644af69370127f9e99d22b4a1d/src/module_NEMS_GRID_COMP.F90#L308

In all cases now, the NEMS EARTH DRIVER runs across all PETs and so specification of the petList parameter to ESMF_GridCompCreate() is not required.

The recommended approach is to remove all PE_MEMBER logic from NEMS.

This also allows for removal of `PE_MEMBER01:` inside `model_configure`.  Its presence there is confusing anyway since that file is a config file for the atmosphere, and not the overall NEMS level.

**Comment by rsdunlapiv** [comment]
@DusanJovic-NOAA @junwang-noaa @mark-a-potts @theurich

**Comment by DusanJovic-NOAA** [comment]
In one of the future commits we will remove `module_NEMS_GRID_COMP.F90` entirely. It does nothing except instantiate Earth Grid Comp, which can be done directly in the main program.
This is the version of the main program that calls Earth Grid Comp directly.
[MAIN_NEMS.F90.txt](https://github.com/NOAA-EMC/NEMS/files/6670121/MAIN_NEMS.F90.txt)
It still reads `PE_MEMBER01` which I just moved from NEMS Grid comp. It should be removed.

**Comment by DusanJovic-NOAA** [comment]
See this branch:
https://github.com/DusanJovic-NOAA/NEMS/tree/remove_nems_grid_comp/src

**Comment by rsdunlapiv** [comment]
@DusanJovic-NOAA I like the simplicity of this.  NEMS is getting very small.  This is basically just the unified driver now.  @theurich @mark-a-potts
