### ISSUE TITLE
merge hot fixes in public release branch to develop branch

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/NEMS#34]
When the public release branch is finalized, the hot fixes needs to be committed to develop branch.

It includes:
1. fixes problem with MPI_Comm_Split in openmpi when hash is negative (https://github.com/NOAA-EMC/NEMS/pull/25)
2. Set default values for model_configure variables (https://github.com/NOAA-EMC/NEMS/pull/18)

**Comment by MinsukJi-NOAA** [comment]
This merge has been tested and committed (#45)
